# Generated by Django 4.2.24 on 2025-10-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('icon', models.CharField(choices=[('MagnifyingGlassIcon', 'MagnifyingGlassIcon'), ('CubeIcon', 'CubeIcon'), ('DocumentDuplicateIcon', 'DocumentDuplicateIcon'), ('ArrowDownTrayIcon', 'ArrowDownTrayIcon'), ('ShieldCheckIcon', 'ShieldCheckIcon'), ('ArrowsRightLeftIcon', 'ArrowsRightLeftIcon'), ('DocumentArrowUpIcon', 'DocumentArrowUpIcon'), ('TableCellsIcon', 'TableCellsIcon')], max_length=50)),
            ],
        ),
    ]
